### ISSUE TITLE
Template Project doesnt work as intended (AbpMvcAuthorize doesnt work)

### ISSUE THREAD

**Issue by Korigoth** [aspnetboilerplate/aspnetboilerplate-templates#15]
Download the Project Template with AbpZero

Set .Web Project as StartUp Project
Restore Nugget Package, 
Run Update-databe
Play

First it shouldn't be possible to go to /#/ page  without prior connection.
But it goes there and fail...

AbpMvcAuthorize didn't do his job.

Chrome console errors:  (they are there because it doesnt redirect to login page when i was not connected)
TypeError: Cannot read property 'userName' of null
    at vm.getShownUserName (http://localhost:6334/App/Main/views/layout/header.js:20:43)
    at fn (eval at <anonymous> (http://localhost:6334/Scripts/angular.min.js:212:283), <anonymous>:4:243)
    at Object.get (http://localhost:6334/Scripts/angular.min.js:114:129)
    at n.$digest (http://localhost:6334/Scripts/angular.min.js:130:71)
    at n.$apply (http://localhost:6334/Scripts/angular.min.js:133:236)
    at g (http://localhost:6334/Scripts/angular.min.js:87:376)
    at K (http://localhost:6334/Scripts/angular.min.js:91:448)
    at XMLHttpRequest.z.onload (http://localhost:6334/Scripts/angular.min.js:92:462)(anonymous function) @ angular.min.js:107
http://localhost:6334/fonts/fontawesome-webfont.woff2?v=4.4.0 Failed to load resource: the server responded with a status of 404 (Not Found)
angular.min.js:107 TypeError: Cannot read property 'userName' of null
    at vm.getShownUserName (http://localhost:6334/App/Main/views/layout/header.js:20:43)
    at fn (eval at <anonymous> (http://localhost:6334/Scripts/angular.min.js:212:283), <anonymous>:4:243)
    at Object.get (http://localhost:6334/Scripts/angular.min.js:114:129)
    at n.$digest (http://localhost:6334/Scripts/angular.min.js:130:71)
    at http://localhost:6334/Scripts/angular.min.js:133:32
    at e (http://localhost:6334/Scripts/angular.min.js:43:95)
    at http://localhost:6334/Scripts/angular.min.js:45:491(anonymous function) @ angular.min.js:107
2angular.min.js:107 TypeError: Cannot read property 'userName' of null
    at vm.getShownUserName (http://localhost:6334/App/Main/views/layout/header.js:20:43)
    at fn (eval at <anonymous> (http://localhost:6334/Scripts/angular.min.js:212:283), <anonymous>:4:243)
    at Object.get (http://localhost:6334/Scripts/angular.min.js:114:129)
    at n.$digest (http://localhost:6334/Scripts/angular.min.js:130:71)
    at n.$apply (http://localhost:6334/Scripts/angular.min.js:133:236)
    at g (http://localhost:6334/Scripts/angular.min.js:87:376)
    at K (http://localhost:6334/Scripts/angular.min.js:91:448)
    at XMLHttpRequest.z.onload (http://localhost:6334/Scripts/angular.min.js:92:462)(anonymous function) @ angular.min.js:107
2angular.min.js:107 TypeError: Cannot read property 'userName' of null
    at vm.getShownUserName (http://localhost:6334/App/Main/views/layout/header.js:20:43)
    at fn (eval at <anonymous> (http://localhost:6334/Scripts/angular.min.js:212:283), <anonymous>:4:243)
    at Object.get (http://localhost:6334/Scripts/angular.min.js:114:129)
    at n.$digest (http://localhost:6334/Scripts/angular.min.js:130:71)
    at http://localhost:6334/Scripts/angular.min.js:133:32
    at e (http://localhost:6334/Scripts/angular.min.js:43:95)
    at http://localhost:6334/Scripts/angular.min.js:45:491

**Comment by Korigoth** [comment]
Ok this happenned only on the  first play... dont know why...

**Comment by hikalkan** [comment]
Maybe you did run another project in the same port before and it somehow cached.

**Comment by Korigoth** [comment]
You got it. I always forgot to change the Port of the WebSite before starting it. So it was cached and when i press F5 (i disable cache by default) it's refreshing the WebSite.
