### ISSUE TITLE
RoleManager.Roles throws System.MissingMethodException

### ISSUE THREAD

**Issue by jseger** [aspnetboilerplate/aspnetboilerplate-templates#68]
Upon further investigation, it appears that the type RoleManagerProxy could not be found.

To recreate: 
1. Create an ASP.NET MVC 5 template.
2. Try to register a new user.

Using Abp version 2.02.  Can't seem to update because Castle.Core can't update because Castle.LoggingFacility 3.4.0 is holding it back.

**Comment by jseger** [comment]
Can anyone recreate this issue??

**Comment by jseger** [comment]
FYI.  EventCloud demo seems to work fine.  I'll try and see what the difference is.

**Comment by ismcagdas** [comment]
Hi @jseger,

Is there any detailed error message in Logs.txt file under your web project ?

**Comment by jseger** [comment]
ERROR 2017-07-05 15:26:28,123 [29   ] aWorks.Web.Controllers.AccountController - Method not found: 'System.String Abp.Runtime.Security.SimpleStringCipher.Decrypt(System.String, System.String, Byte[])'.
System.MissingMethodException: Method not found: 'System.String Abp.Runtime.Security.SimpleStringCipher.Decrypt(System.String, System.String, Byte[])'.
   at Abp.MultiTenancy.TenantCache`2.CreateTenantCacheItem(TTenant tenant)
   at Castle.Proxies.Invocations.TenantCache`2_CreateTenantCacheItem.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.TenantCache`2Proxy.CreateTenantCacheItem(Tenant tenant)
   at Abp.Runtime.Caching.CacheExtensions.<>c__DisplayClass3_0`2.<Get>b__0(String k)
   at Abp.Runtime.Caching.CacheBase.Get(String key, Func`2 factory)
   at Abp.Runtime.Caching.CacheExtensions.Get[TKey,TValue](ICache cache, TKey key, Func`2 factory)
   at Abp.MultiTenancy.TenantCache`2.Get(Int32 tenantId)
   at Castle.Proxies.Invocations.TenantCache`2_Get.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.TenantCache`2Proxy.Get(Int32 tenantId)
   at Abp.Zero.EntityFramework.DbPerTenantConnectionStringResolver.GetNameOrConnectionString(DbPerTenantConnectionStringResolveArgs args)
   at Abp.Zero.EntityFramework.DbPerTenantConnectionStringResolver.GetNameOrConnectionString(ConnectionStringResolveArgs args)
   at Abp.EntityFramework.Uow.EfUnitOfWork.GetOrCreateDbContext[TDbContext](Nullable`1 multiTenancySide)
   at Castle.Proxies.EfRepositoryBase`2Proxy_2.get_Context_callback()
   at Castle.Proxies.Invocations.EfRepositoryBase`3_get_Context_9.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Abp.Domain.Uow.UnitOfWorkInterceptor.PerformSyncUow(IInvocation invocation, UnitOfWorkOptions options)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.EfRepositoryBase`2Proxy_2.get_Context()
   at Abp.EntityFramework.Repositories.EfRepositoryBase`3.get_Table()
   at Castle.Proxies.Invocations.EfRepositoryBase`3_get_Table_9.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Abp.Domain.Uow.UnitOfWorkInterceptor.PerformSyncUow(IInvocation invocation, UnitOfWorkOptions options)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.EfRepositoryBase`2Proxy_2.get_Table()
   at Castle.Proxies.EfRepositoryBase`2Proxy_2.GetAll_callback()
   at Castle.Proxies.Invocations.EfRepositoryBase`3_GetAll_9.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Abp.Domain.Uow.UnitOfWorkInterceptor.PerformSyncUow(IInvocation invocation, UnitOfWorkOptions options)
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.EfRepositoryBase`2Proxy_2.GetAll()
   at Castle.Proxies.Invocations.RoleManager`2_get_Roles.InvokeMethodOnTarget()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.DynamicProxy.AbstractInvocation.Proceed()
   at Castle.Proxies.RoleManagerProxy.get_Roles()

**Comment by ismcagdas** [comment]
Updating all ABP nuget packages should solve this problem.
Today, I have downloaded a sample project from ABP website, upgraded all ABP nuget packages, added a new migration and project is working for me.

I couldn't understand why you had problem with Castle nuget packages.
